version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"  

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"  
    depends_on:
      - backend  


networks:
  app-network:
    driver: bridge